# Generated by Django 4.1.3 on 2022-12-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_permitted', models.BooleanField(default=False, verbose_name='Разрешенный?')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата начала')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звоноки',
                'ordering': ['-updated_at'],
            },
        ),
    ]
