# Generated by Django 4.1.3 on 2022-12-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('massage', models.CharField(max_length=255, verbose_name='Массажа')),
                ('time', models.IntegerField(verbose_name='Кол-во минут')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заказ сертификата',
                'verbose_name_plural': 'Заказы сертификатов',
                'ordering': ['-created_at'],
            },
        ),
    ]
